#!/usr/bin/env python3
import argparse
import json
import sys
import uuid


def emit(status, summary, details=None):
    payload = {
        "status": status,
        "summary": summary,
        "details": details or {},
    }
    print(json.dumps(payload))


def build_validator(ge, df):
    if hasattr(ge, "from_pandas"):
        return ge.from_pandas(df)

    context = ge.get_context()
    datasource_name = f"tmp_ge_audit_ds_{uuid.uuid4().hex[:8]}"
    asset_name = f"tmp_ge_audit_asset_{uuid.uuid4().hex[:8]}"
    suite_name = f"tmp_ge_audit_suite_{uuid.uuid4().hex[:8]}"

    datasource = context.data_sources.add_pandas(name=datasource_name)
    asset = datasource.add_dataframe_asset(name=asset_name)
    batch_definition = asset.add_batch_definition_whole_dataframe("whole_dataframe")
    batch = batch_definition.get_batch(batch_parameters={"dataframe": df})

    return context.get_validator(
        batch=batch,
        create_expectation_suite_with_name=suite_name,
    )


def normalize_check_result(check):
    if hasattr(check, "to_json_dict"):
        return check.to_json_dict()
    if isinstance(check, dict):
        return check
    return {
        "success": bool(getattr(check, "success", False)),
        "expectation_config": {
            "expectation_type": getattr(
                getattr(check, "expectation_config", None),
                "expectation_type",
                None,
            )
        },
        "result": getattr(check, "result", None),
    }


def main():
    parser = argparse.ArgumentParser(description="Great Expectations audit for master-script chunks.")
    parser.add_argument("--input", required=True, help="Path to JSON payload generated by service")
    args = parser.parse_args()

    try:
        import pandas as pd  # type: ignore
        import great_expectations as ge  # type: ignore
    except Exception as exc:
        emit("skipped", f"Great Expectations audit skipped: {exc}")
        return 0

    with open(args.input, "r", encoding="utf-8") as f:
        payload = json.load(f)

    rows = payload.get("rows", [])
    expected_count = int(payload.get("expectedChunkCount", len(rows)))

    if not rows:
        emit("failed", "No rows provided to GE audit.")
        return 0

    try:
        df = pd.DataFrame(rows)
        gdf = build_validator(ge, df)

        checks = []
        checks.append(gdf.expect_table_row_count_to_equal(expected_count))
        checks.append(gdf.expect_column_values_to_not_be_null("chunkId"))
        checks.append(gdf.expect_column_values_to_be_unique("chunkId"))
        checks.append(gdf.expect_column_values_to_not_be_null("scriptVersion"))
        checks.append(gdf.expect_column_values_to_not_be_null("sceneSeq"))
        checks.append(gdf.expect_column_values_to_not_be_null("elementSeq"))
        checks.append(gdf.expect_column_values_to_not_be_null("elementType"))
        checks.append(gdf.expect_column_values_to_not_be_null("sourceStartLine"))
        checks.append(gdf.expect_column_values_to_not_be_null("sourceEndLine"))
        checks.append(
            gdf.expect_column_pair_values_a_to_be_greater_than_b(
                "sourceEndLine",
                "sourceStartLine",
                or_equal=True,
            )
        )
        checks.append(gdf.expect_column_values_to_not_be_null("parentNodeId"))
    except Exception as exc:
        emit("skipped", f"GE audit skipped: {exc}")
        return 0

    normalized_checks = [normalize_check_result(check) for check in checks]

    all_success = all(bool(check.get("success")) for check in normalized_checks)
    details = {
        "expectationCount": len(normalized_checks),
        "failedExpectations": [
            {
                "expectation": (
                    check.get("expectation_config", {}).get("expectation_type")
                    or check.get("expectation_config", {}).get("type")
                ),
                "result": check.get("result"),
            }
            for check in normalized_checks
            if not bool(check.get("success"))
        ],
    }

    if all_success:
        emit("passed", "GE audit passed for master-script chunk dataset.", details)
    else:
        emit("failed", "GE audit failed for master-script chunk dataset.", details)
    return 0


if __name__ == "__main__":
    sys.exit(main())
